
function [common_location] = generate_common_location(common_labels, labels, location)
% GENERATE COMMON LOCATION the purpose of this function is to regenerate
% the channels location that were lost when calling the get_subset
% function.
%   When we call the get_subset function used in the previous dpli-dri
%   analysis we do not have any channels location information. This was not
%   needed since the dpli analysis is agnostic of where in the brain the
%   channels are. However, for the hub analysis this is an important
%   information. Here we take the common_labels that were generated by
%   get_subset and we regenerate the channels location using the location
%   from one of the state
%
%   input:
%   common_labels: A cell array containing all the labels that are common
%   everywhere in the states
%   location: A given location structure that was used to generate the
%   common_labels.
%
%   output:
%   common_location: this is an array of struct containing all the channels
%   information

    common_location = [];
    for l = 1:length(common_labels)
       label = common_labels{l};
       
       % will find where this label appear in the location
       index = get_label_index(label, labels);
        
       % store the location in the common_location structure
       common_location = [common_location, location(index)];
    end
end
